### ISSUE TITLE
Crash when public key invalid

### ISSUE THREAD

**Issue by TeruyaHaroldo** [wultra/ssl-pinning-ios#18] opened 2021-04-26 19:07 UTC
Hello, my name is Haroldo.
I am having the following issue:

```swift
let configuration = CertStoreConfiguration(
    serviceUrl: serviceUrl,
    publicKey: publicKey // invalid public key.
)

let certStore = CertStore.powerAuthCertStore(configuration: configuration) // <- crash here.
```

The correct, is to the `certStore.update` give a error response. Right?

**Comment by petrdvorak** [comment] 2021-04-26 19:56
Hello @TeruyaHaroldo, thank you for the report - we will discuss this internally for a while but I am inclining toward closing the issue. Having an invalid public key in the configuration object is generally a configuration issue that should be resolved in app compile time. Crash clearly indicates something is wrong and the developer cannot overlook it. Crashing can be therefore considered a correct reaction by the app, and it is currently by design as indicated here:

https://github.com/wultra/ssl-pinning-ios/blob/1615551e5e1a461abfeef479eea1fa50de68826d/Source/Lib/CertStoreConfiguration.swift#L162

**Comment by TeruyaHaroldo** [comment] 2021-04-26 19:59
Understood @petrdvorak. Thank you for your response.

**Closed** 2021-04-26 22:22 UTC
